from dataclasses import dataclass
from enum import Enum


class LanguageTokenization(Enum):
    CJK = "cjk"
    SPACE = "space"


@dataclass(frozen=True)
class LanguageOptions:
    tokenization: LanguageTokenization
    name: str


class Language(Enum):
    AF = LanguageOptions(LanguageTokenization.SPACE, "Afrikaans")
    SQ = LanguageOptions(LanguageTokenization.SPACE, "Albanian")
    AM = LanguageOptions(LanguageTokenization.SPACE, "Amharic")
    AR = LanguageOptions(LanguageTokenization.SPACE, "Arabic")
    HY = LanguageOptions(LanguageTokenization.SPACE, "Armenian")
    AZ = LanguageOptions(LanguageTokenization.SPACE, "Azerbaijani")
    EU = LanguageOptions(LanguageTokenization.SPACE, "Basque")
    BE = LanguageOptions(LanguageTokenization.SPACE, "Belarusian")
    BN = LanguageOptions(LanguageTokenization.SPACE, "Bengali")
    BS = LanguageOptions(LanguageTokenization.SPACE, "Bosnian")
    BG = LanguageOptions(LanguageTokenization.SPACE, "Bulgarian")
    MY = LanguageOptions(LanguageTokenization.CJK, "Burmese")
    CA = LanguageOptions(LanguageTokenization.SPACE, "Catalan")
    ZH = LanguageOptions(LanguageTokenization.CJK, "Chinese")
    HR = LanguageOptions(LanguageTokenization.SPACE, "Croatian")
    CS = LanguageOptions(LanguageTokenization.SPACE, "Czech")
    DA = LanguageOptions(LanguageTokenization.SPACE, "Danish")
    NL = LanguageOptions(LanguageTokenization.SPACE, "Dutch")
    EN = LanguageOptions(LanguageTokenization.SPACE, "English")
    ET = LanguageOptions(LanguageTokenization.SPACE, "Estonian")
    FI = LanguageOptions(LanguageTokenization.SPACE, "Finnish")
    FR = LanguageOptions(LanguageTokenization.SPACE, "French")
    GL = LanguageOptions(LanguageTokenization.SPACE, "Galician")
    KA = LanguageOptions(LanguageTokenization.SPACE, "Georgian")
    DE = LanguageOptions(LanguageTokenization.SPACE, "German")
    EL = LanguageOptions(LanguageTokenization.SPACE, "Greek")
    GU = LanguageOptions(LanguageTokenization.SPACE, "Gujarati")
    HE = LanguageOptions(LanguageTokenization.SPACE, "Hebrew")
    HI = LanguageOptions(LanguageTokenization.SPACE, "Hindi")
    HU = LanguageOptions(LanguageTokenization.SPACE, "Hungarian")
    IS = LanguageOptions(LanguageTokenization.SPACE, "Icelandic")
    ID = LanguageOptions(LanguageTokenization.SPACE, "Indonesian")
    IT = LanguageOptions(LanguageTokenization.SPACE, "Italian")
    JA = LanguageOptions(LanguageTokenization.CJK, "Japanese")
    KN = LanguageOptions(LanguageTokenization.SPACE, "Kannada")
    KK = LanguageOptions(LanguageTokenization.SPACE, "Kazakh")
    KO = LanguageOptions(LanguageTokenization.CJK, "Korean")
    LV = LanguageOptions(LanguageTokenization.SPACE, "Latvian")
    LT = LanguageOptions(LanguageTokenization.SPACE, "Lithuanian")
    MK = LanguageOptions(LanguageTokenization.SPACE, "Macedonian")
    MS = LanguageOptions(LanguageTokenization.SPACE, "Malay")
    ML = LanguageOptions(LanguageTokenization.SPACE, "Malayalam")
    MR = LanguageOptions(LanguageTokenization.SPACE, "Marathi")
    MN = LanguageOptions(LanguageTokenization.SPACE, "Mongolian")
    NE = LanguageOptions(LanguageTokenization.SPACE, "Nepali")
    NO = LanguageOptions(LanguageTokenization.SPACE, "Norwegian")
    FA = LanguageOptions(LanguageTokenization.SPACE, "Persian")
    PL = LanguageOptions(LanguageTokenization.SPACE, "Polish")
    PT = LanguageOptions(LanguageTokenization.SPACE, "Portuguese")
    PA = LanguageOptions(LanguageTokenization.SPACE, "Punjabi")
    RO = LanguageOptions(LanguageTokenization.SPACE, "Romanian")
    RU = LanguageOptions(LanguageTokenization.SPACE, "Russian")
    SR = LanguageOptions(LanguageTokenization.SPACE, "Serbian")
    SI = LanguageOptions(LanguageTokenization.SPACE, "Sinhala")
    SK = LanguageOptions(LanguageTokenization.SPACE, "Slovak")
    SL = LanguageOptions(LanguageTokenization.SPACE, "Slovenian")
    ES = LanguageOptions(LanguageTokenization.SPACE, "Spanish")
    SW = LanguageOptions(LanguageTokenization.SPACE, "Swahili")
    SV = LanguageOptions(LanguageTokenization.SPACE, "Swedish")
    TA = LanguageOptions(LanguageTokenization.SPACE, "Tamil")
    TE = LanguageOptions(LanguageTokenization.SPACE, "Telugu")
    TH = LanguageOptions(LanguageTokenization.CJK, "Thai")
    TR = LanguageOptions(LanguageTokenization.SPACE, "Turkish")
    UK = LanguageOptions(LanguageTokenization.SPACE, "Ukrainian")
    UR = LanguageOptions(LanguageTokenization.SPACE, "Urdu")
    UZ = LanguageOptions(LanguageTokenization.SPACE, "Uzbek")
    VI = LanguageOptions(LanguageTokenization.SPACE, "Vietnamese")
    CY = LanguageOptions(LanguageTokenization.SPACE, "Welsh")
    XH = LanguageOptions(LanguageTokenization.SPACE, "Xhosa")
    ZU = LanguageOptions(LanguageTokenization.SPACE, "Zulu")
